Parameters:
  IntegrationsId:
    Description: "Integrations Id"
    Type: String
  Passkey:
    Description: "Passkey"
    Type: String
    NoEcho: true
  S3DataRetention:
    Type: Number
    Default: 7
    MaxValue: 366
    Description: "Number of days to keep the logs. Max 365"
  SamuraiEndPoint:
    Type: String
    Description: "Samurai Endpoint"
    Default: "api.westeurope.samurai.security.ntt"
    AllowedValues:
      - "api.westeurope.samurai.security.ntt"
      - "api.westeurope.develop.samurai.security.ntt"
  CiscoUmbrella:
    Type: String
    Description: "Add Bucket Policy to support Cisco"
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"

Conditions:
  EnableCiscoUmbrella: !Equals
    - !Ref CiscoUmbrella
    - "Yes"
  DisableCiscoUmbrella: !Equals
    - !Ref CiscoUmbrella
    - "No"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DependsOn:
      - SamuraiSNSTopic
      - SamuraiTopicPolicy
    DeletionPolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketName: !Join
        - "-"
        - - "samurai"
          - !Select
              - 4
              - !Split
                  - '-'
                  - !Select
                      - 2
                      - !Split
                          - /
                          - !Ref AWS::StackId
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref SamuraiSNSTopic
            Event: s3:ObjectCreated:*
      LifecycleConfiguration:
        Rules:
          - Id: purgeData
            Status: Enabled
            ExpirationInDays:
              Ref: S3DataRetention

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: DisableCiscoUmbrella
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
              - 's3:ListBucket'
            Effect: Allow
            Resource: 
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Bucket
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Bucket
                  - /*
            Principal:
              "AWS": "arn:aws:iam::600502389717:user/samurai-xdr-s3-reader-user"

  S3CiscoUmbrellaBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: EnableCiscoUmbrella
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
              - 's3:ListBucket'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Bucket
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Bucket
                  - /*
            Principal:
              "AWS": "arn:aws:iam::600502389717:user/samurai-xdr-s3-reader-user"
          - Sid: ''
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::568526795995:user/logs'
            Action: 's3:PutObject'
            Resource: !Join
                        - ''
                        - - 'arn:aws:s3:::'
                          - !Ref S3Bucket
                          - /*
          - Sid: ''
            Effect: Deny
            Principal:
              AWS: 'arn:aws:iam::568526795995:user/logs'
            Action: 's3:GetObject'
            Resource: !Join
                        - ''
                        - - 'arn:aws:s3:::'
                          - !Ref S3Bucket
                          - /*
          - Sid: ''
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::568526795995:user/logs'
            Action: 's3:GetBucketLocation'
            Resource: !Join
                        - ''
                        - - 'arn:aws:s3:::'
                          - !Ref S3Bucket
          - Sid: ''
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::568526795995:user/logs'
            Action: 's3:ListBucket'
            Resource: !Join
                        - ''
                        - - 'arn:aws:s3:::'
                          - !Ref S3Bucket


  SamuraiWebhookSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref SamuraiSNSTopic
      Endpoint: !Sub
        - "https://${Domain}/integrations/aws_s3/${Integrations_id}/${Passkey}"
        - Domain: !Ref SamuraiEndPoint
          Integrations_id: !Ref IntegrationsId
          Passkey: !Ref Passkey
      Protocol: https
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 20
          minDelayTarget: 10
          maxDelayTarget: 30
          numMinDelayRetries: 3
          numMaxDelayRetries: 17
          numNoDelayRetries: 0
          backoffFunction: exponential

  SamuraiSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Join
        - "-"
        - - "samurai"
          - !Select
              - 4
              - !Split
                  - '-'
                  - !Select
                      - 2
                      - !Split
                          - /
                          - !Ref AWS::StackId

  SamuraiTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Sid: AllowS3Services
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action: 'sns:Publish'
            Resource:
              - !Ref SamuraiSNSTopic
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Join
                  - ""
                  - - "arn:aws:s3:::"
                    - "samurai-"
                    - !Select
                        - 4
                        - !Split
                            - '-'
                            - !Select
                                - 2
                                - !Split
                                    - /
                                    - !Ref AWS::StackId


      Topics:
        - !Ref SamuraiSNSTopic
Outputs:
  SamuraiS3Bucket:
    Description: Samurai XDR S3 bucket Arn
    Value: !GetAtt S3Bucket.Arn
  SamuraiS3BucketName:
    Description: Samurai XDR S3 bucket Arn
    Value: !Ref S3Bucket
